server_port: 8090
neo4j:
  uri: bolt://192.168.1.104:30333
  username: ""
  password: ""
# database:
#   uri: mongodb://192.168.1.21:27017
#   dbname: test
#   username: admin
#   password: admin@123
